### PR TITLE
Adding Error Handler

### LINKED ISSUE #149: A basic error handler
Create a basic error handler, with these 3 custom errors:
- `MeiliSearchApiError`
- `MeiliSearchCommunicationError`
- `MeiliSearchTimeoutError`

MeiliSearch API has an error handler, and returns this kind of JSON when an error is found:

```json
{
  "message": "Index movies not found",
  "errorCode": "index_not_found",
  "errorType": "invalid_request_error",
  "errorLink": "https://docs.meilisearch.com/errors#index_not_found"
}
```
The complete list of errorCode is available in the [documentation](https://docs.meilisearch.com/errors)

It could be great to let the user access `message`, `errorCode`, `errorType` and `errorLink` to a better understanding an error.

### LINKED ISSUE #161: Add timeout in client
**Description**
Adding the possibility of declaring a timeout in the client.
Perform all the requests and wait for a response during the given timeout duration.
ErrTimeout is returned if the response wasn't returned during the given timeout.

**Basic example**
``` go
var client = NewClient(ClientConfig{
	Host:      "http://localhost:7700",
	MasterKey: masterKey,
	Timeout:   10 * time.Minute,
})
```

### PR DESCRIPTION
**Pull request by alallema**
**Description**
Adapt to the error handler of other SDKs with 3 main errors type:

- MeiliSearchApiError
- MeiliSearchCommunicationError
- MeiliSearchTimeoutError

Add the possibility to set a timeout in the client for all the requests passed.

**Issue related**
closes #149
closes #161

### CODE REVIEW

**Comment by curquiza** [comment]
@alallema, be careful, GH did not add your issue as a `Linked issues` in this PR 😅

**Comment by alallema** [comment]
> @alallema, be careful, GH did not add your issue as a `Linked issues` in this PR 😅

Thanks, @curquiza! It's a draft I didn't finish to edit it

**Review by eskombro — CHANGES_REQUESTED** [review]
Amazing job @alallema !

I would add an Issue that details a little bit the Timeout handling that is included in this PR, and link it to the PR. Because this timeout change is not only related to the custom error handler, but actually adds some functionality to the HTTP client.

**Review by eskombro — COMMENTED** [review]
Amazing job @alallema !

I would add an Issue that details a little bit the Timeout handling that is included in this PR, and link it to the PR. Because this timeout change is not only related to the custom error handler, but actually adds some functionality to the HTTP client.

**Review by curquiza — APPROVED** [review]
Awesome!! Thanks @alallema!!

**Comment by curquiza** [comment]
@alallema this PR is breaking from my POV

**Comment by alallema** [comment]
Issue created
bors merge

**Pull request merged**
