### PR TITLE
Add makefile and badges for readme

### PR DESCRIPTION
**Pull request by Ja7ad**
## What does this PR do?
- This PR add codecov and go reference badge in readme and add makefile for easyjson and test.

## PR checklist
Please check if your PR fulfills the following requirements:
- [ ] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Review by curquiza — CHANGES_REQUESTED** [review]
Thanks @Ja7ad for the PR, as usual ❤️

Can you update our CONTRIBUTING to explain how to use the makefile -> at Meilisearch, we are not familiar with Go good practices and since we manage a lot of different environment, we need CONTRIBUTING to guide us when coming back on the repo 😊

**Comment by Ja7ad** [comment]
> Thanks @Ja7ad for the PR, as usual ❤️
> 
> Can you update our CONTRIBUTING to explain how to use the makefile -> at Meilisearch, we are not familiar with Go good practices and since we manage a lot of different environment, we need CONTRIBUTING to guide us when coming back on the repo 😊 

I will update it

**Comment by Ja7ad** [comment]
@curquiza Updated `CONTRIBUTING.md`

**Review by curquiza — APPROVED** [review]
thank you

bors merge

**Pull request merged**
