### PR TITLE
Add AI-powered search changes related to v1.10

### LINKED ISSUE #576: [v1.10.0] AI-powered search changes
*Following this [central issue](https://github.com/meilisearch/integration-guides/issues/302)*

### Explanation of the feature

- Rest embedder
  - Removed parameters: `query`, `inputField`, `inputType`, `pathToEmbeddings` and `embeddingObject`.
  - Replaced by `request` and `response`
  - New parameter: `headers`
- Add `url` parameter to the OpenAI embedder
- `dimensions` is now available as an optional parameter for `ollama` embedders.

Usage: https://meilisearch.notion.site/v1-10-AI-search-changes-737c9d7d010d4dd685582bf5dab579e2?pvs=74

### TODO

- [x] Rest embedder
  - [x] Remove the following parameters: `query`, `inputField`, `inputType`, `pathToEmbeddings` and `embeddingObject`.
  - [x] Add the new parameters `request`, `response` and `headers` (cf usage for more information)
- [x] Add `url` parameter to the OpenAI embedder
- [x] Add `dimensions` for Ollama embedders.
- [x] Update the tests accordingly

### PR DESCRIPTION
**Pull request by Ja7ad**
# Pull Request

## Related issue
Fixes #576 

## What does this PR do?
- Update the embedders types + tests according to v1.10 
- Fix name convation for "APIKey" instead "ApiKey".

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by curquiza** [comment]
@Ja7ad is this breaking?
If yes, can you list the breaking changes for the users (in PR description)?
To be clear, I have not issue with breaking of course, we just need clarity.

**Comment by Ja7ad** [comment]
> @Ja7ad is this breaking?
> If yes, can you list the breaking changes for the users (in PR description)?
> To be clear, I have not issue with breaking of course, we just need clarity.

Based on issue, it's breaking changes.

**Comment by curquiza** [comment]
I asked because I see you also changed the name of APIkey into ApiKey, and it's not part of the issue

**Comment by Ja7ad** [comment]
> I asked because I see you also changed the name of Apikey into APIKey, and it's not part of the issue. Is there any other changes?

Revert it?

**Comment by curquiza** [comment]
@Ja7ad I'm not sure what you mean here
I want to know what are the breaking changes for users in this PR
Of course, there is the changes asked in the issues. But is there any other changes? I see in the PRs you also took the opportunity to change naming that are not asked in the issue. So now I'm asking if there is another other changes like this in the PR that are breaking for users? I need this information to deliver a clear changelogs

**Comment by Ja7ad** [comment]
> @Ja7ad I'm not sure what you mean here
> I want to know what are the breaking changes for users in this PR
> Of course, there is the changes asked in the issues. But is there any other changes? I see in the PRs you also took the opportunity to change naming that are not asked in the issue. So now I'm asking if there is another other changes like this in the PR that are breaking for users? I need this information to deliver a clear changelogs 

I mean do you want revert name of "ApiKey"?

**Comment by curquiza** [comment]
> I mean do you want revert name of "ApiKey"?

No I don't want, I trust you on what are the best changes.
But I need you to be clear in the PR description about the changes you made, so that I can document it clearly in the changelogs

**Comment by Ja7ad** [comment]
> > I mean do you want revert name of "ApiKey"?
> 
> No I don't want, I trust you on what are the best changes.
> But I need you to be clear in the PR description about the changes you made, so that I can document it clearly in the changelogs

The word API is an abbreviation of three words and, in terms of naming convention, is better written as "API" instead of "Api".

**Review by curquiza — APPROVED** [review]
bors merge

**Pull request merged**
