### PR TITLE
Refactor meilisearch client wtih new client and documentation

### LINKED ISSUE #462: API doesn't take context.Context
every network operation in Go should take a context, so it can be cancelled and proper deadlines applied. This is only available in the task waiting api and even there in a non-standard manner

### LINKED ISSUE #554: Using built-in http.Client instead fasthttp.Client
The fasthttp library isn't very appealing as a client and is mostly used on the server side. However, its only advantage is the use of sync.Pool to reuse an object and improve memory usage.

But as an SDK client, we need to try to use built-in packages to avoid package conflicts for users during usage. Most major SDKs like AWS and Google Cloud use the built-in HTTP client package.

- https://github.com/aws/aws-sdk-go
- https://github.com/googleapis/google-cloud-go

However, regarding context.Context, we need to receive a higher-level stop signal so that the request can be halted.

#462

There are many solutions to improve the performance of http.Client, and we can enhance it quite easily.

We are currently unstable and we can improve our sdk 🚀, I can refactor it for stable.

### PR DESCRIPTION
**Pull request by Ja7ad**
# Pull Request

## Related issue
Resolves #554, resolves #462 

## What does this PR do?
- Refactor client to http.Client with optimized configuration
- Support parent context for all methods
- Add option pattern for optional configuration of constructor
- Improved documentation package, methods
- This refactor make better experience usage sdk for developers.

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by Ja7ad** [comment]
I will fix coverage issue in another PR on branch `refactor`

**Comment by curquiza** [comment]
Thanks @Ja7ad 

Tring to review this is week

**Comment by Ja7ad** [comment]
> Hello @Ja7ad
> 
> So that I can review, can you make the exhaustive list of breaking changes for the user please?
> 
> Like
> 
> ```go
> // Before
> client := meilisearch.NewClient(meilisearch.ClientConfig{
> 	client := meilisearch.New("http://localhost:7700", meilisearch.WithAPIKey("foobar"))
>                 Host: "http://127.0.0.1:7700",
> 
>                 APIKey: "masterKey",
>         })
> 
> // Now
> client := meilisearch.New("http://localhost:7700", meilisearch.WithAPIKey("foobar"))
> ```

Hello Sure, can you help me to do this?

**Comment by Ja7ad** [comment]
> Hello @Ja7ad 
> 
> So that I can review, can you make the exhaustive list of breaking changes for the user please?
> 
> Like
> 
> ```go
> // Before
> client := meilisearch.NewClient(meilisearch.ClientConfig{
> 	client := meilisearch.New("http://localhost:7700", meilisearch.WithAPIKey("foobar"))
>                 Host: "http://127.0.0.1:7700",
> 
>                 APIKey: "masterKey",
>         })
> 
> // Now
> client := meilisearch.New("http://localhost:7700", meilisearch.WithAPIKey("foobar"))
> ```

Hello sure, fixed

**Comment by Ja7ad** [comment]
@curquiza Hello

This PR currently hold for review.
I fixed coverage issue or this PR on next PR for `refactor` branch?

**Pull request merged**
