### PR TITLE
Fix add json tag on search request

### LINKED ISSUE #531: Add json tags to request/query types
**Description**
I would like to be able to proxy incoming requests from my front-end via the Go SDK. For this to work I need to unmarshal my request body received from the front-end into `meilisearch.MultiSearchRequest`, however, since this struct does not have json tags it does not work using the standard `json.Unmarshal()` function. Using the `UnmarshalJSON()` method on the request type itself doesn't work as some of the fields are represented differently. e.g. 'q' becomes 'Query'.

I would like to propose adding json tags to all request/query types just as they exist in the return types to make it easier to construct this type from raw json.

**Basic example**
It should be as simple as 
```go
// Unmarshal the request body into a MultiSearchRequest
searchReq := &meilisearch.MultiSearchRequest{} 
err = searchReq.UnmarshalJSON(reqBytes)
if err != nil {
    return nil, fmt.Errorf("error unmarshaling into meilisearch.MultiSearchRequest: %w", err)
}

// Perform the search
searchRes, err := client.MultiSearch(searchReq)
if err != nil {
    return nil, fmt.Errorf("error during Search: %w", err)
}

// Marshal the search response
searchResBytes, err := searchRes.MarshalJSON()
if err != nil {
    return nil, fmt.Errorf("error marshaling meilisearch.MultiSearchResponse: %w", err)
}
```

**Other**
As a workaround I have added my own struct type and methods to Unmarshal correctly:
```go
// Unmarshal the request body into a MultiSearchRequest
searchReq := &MultiSearchRequest{}             // My type
err = json.Unmarshal(reqBytes, searchReq)  //  Use std lib Unmarshal
    if err != nil {
    return nil, fmt.Errorf("error unmarshaling into MultiSearchRequest: %w", err)
}

// Perform the search
searchRes, err := client.MultiSearch(toMeiliMultiSearchRequest(searchReq))   // convert my request type to meiliesearch type
if err != nil {
    return nil, fmt.Errorf("error during Search: %w", err)
}

type MultiSearchRequest struct {
	Queries []SearchRequest `json:"queries"`
}

type SearchRequest struct {
	Offset                  int64                `json:"offset,omitempty"`
	Limit                   int64                `json:"limit,omitempty"`
	AttributesToRetrieve    []string             `json:"attributesToRetrieve,omitempty"`
	AttributesToSearchOn    []string             `json:"attributesToSearchOn,omitempty"`
	AttributesToCrop        []string             `json:"attributesToCrop,omitempty"`
	CropLength              int64                `json:"cropLength,omitempty"`
	CropMarker              string               `json:"cropMarker,omitempty"`
	AttributesToHighlight   []string             `json:"attributesToHighlight,omitempty"`
	HighlightPreTag         string               `json:"highlightPreTag,omitempty"`
	HighlightPostTag        string               `json:"highlightPostTag,omitempty"`
	MatchingStrategy        string               `json:"matchingStrategy,omitempty"`
	Filter                  interface{}          `json:"filter,omitempty"`
	ShowMatchesPosition     bool                 `json:"showMatchesPosition,omitempty"`
	ShowRankingScore        bool                 `json:"showRankingScore,omitempty"`
	ShowRankingScoreDetails bool                 `json:"showRankingScoreDetails,omitempty"`
	Facets                  []string             `json:"facets,omitempty"`
	PlaceholderSearch       bool                 `json:"placeholderSearch,omitempty"`
	Sort                    []string             `json:"sort,omitempty"`
	Vector                  []float32            `json:"vector,omitempty"`
	HitsPerPage             int64                `json:"hitsPerPage,omitempty"`
	Page                    int64                `json:"page,omitempty"`
	IndexUID                string               `json:"indexUid"`
	Query                   string               `json:"q"`
	Hybrid                  *SearchRequestHybrid `json:"hybrid,omitempty"`
}

type SearchRequestHybrid struct {
	SemanticRatio float64 `json:"semanticRatio,omitempty"`
	Embedder      string  `json:"embedder,omitempty"`
}

func toMeiliSearchRequest(sr SearchRequest) meilisearch.SearchRequest {
	return meilisearch.SearchRequest{
		Offset:                  sr.Offset,
		Limit:                   sr.Limit,
		AttributesToRetrieve:    sr.AttributesToRetrieve,
		AttributesToSearchOn:    sr.AttributesToSearchOn,
		AttributesToCrop:        sr.AttributesToCrop,
		CropLength:              sr.CropLength,
		CropMarker:              sr.CropMarker,
		AttributesToHighlight:   sr.AttributesToHighlight,
		HighlightPreTag:         sr.HighlightPreTag,
		HighlightPostTag:        sr.HighlightPostTag,
		MatchingStrategy:        sr.MatchingStrategy,
		Filter:                  sr.Filter,
		ShowMatchesPosition:     sr.ShowMatchesPosition,
		ShowRankingScore:        sr.ShowRankingScore,
		ShowRankingScoreDetails: sr.ShowRankingScoreDetails,
		Facets:                  sr.Facets,
		PlaceholderSearch:       sr.PlaceholderSearch,
		Sort:                    sr.Sort,
		Vector:                  sr.Vector,
		HitsPerPage:             sr.HitsPerPage,
		Page:                    sr.Page,
		IndexUID:                sr.IndexUID,
		Query:                   sr.Query,
		Hybrid:                  toMeiliSearchRequestHybrid(sr.Hybrid),
	}
}

func toMeiliSearchRequestHybrid(srh *SearchRequestHybrid) *meilisearch.SearchRequestHybrid {
	if srh == nil {
		return nil
	}
	return &meilisearch.SearchRequestHybrid{
		SemanticRatio: srh.SemanticRatio,
		Embedder:      srh.Embedder,
	}
}

func toMeiliMultiSearchRequest(msr *MultiSearchRequest) *meilisearch.MultiSearchRequest {
	queries := make([]meilisearch.SearchRequest, len(msr.Queries))
	for i, q := range msr.Queries {
		queries[i] = toMeiliSearchRequest(q)
	}
	return &meilisearch.MultiSearchRequest{
		Queries: queries,
	}
}
```

### LINKED ISSUE #536: Omitting `Hybrid.Embedder` selects `""` not `"default"`
**Description**
https://github.com/meilisearch/meilisearch-go/blob/0131c589e0fe9a02510dddb1f74b42ec34a45837/index_search.go#L150-L155

Due to L152, `""` will be send to the API if `request.Hybrid.Embedder` is `""`, which is the zero value of string type in Golang.

Should it be fixed as follows?

```go
if request.Hybrid.Embedder != "" {
  hybrid["embedder"] = request.Hybrid.Embedder
}
```

**Expected behavior**

image

I expected that omitting `Embedder` selects the `"default"` embedder as document says.

**Current behavior**

The SDK sends `""` to the server and it responds with the following error:

> ```
> Cannot find embedder with name ``.
> Code: invalid_embedder
> Type: invalid_request
> Link: https://docs.meilisearch.com/errors#invalid_embedder (path "POST /indexes/CatalogItems/search" with method "Search")
> ```

**Environment (please complete the following information):**
- OS: Debian GNU/Linux
- Meilisearch version: v0.18.1
- meilisearch-go version: v0.26.3

### PR DESCRIPTION
**Pull request by Ja7ad**
# Pull Request

## Related issue
Resolves #531, resolves #536

## What does this PR do?
- This PR add json tags to request/query types

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by curquiza** [comment]
@Ja7ad sorry but can you fix the git conflicts on this PR?

**Comment by Ja7ad** [comment]
> @Ja7ad sorry but can you fix the git conflicts on this PR?

I will fix it.

**Comment by curquiza** [comment]
A question @Ja7ad 
Is this PR breaking regarding the usage: I see some tests changing.

I have no issue with releasing breaking change (we are not stable yet), I just need to know it to ensure the appropriate communication and versioning 😊

**Comment by Ja7ad** [comment]
> A question @Ja7ad Is this PR breaking regarding the usage: I see some tests changing.
> 
> I have no issue with releasing breaking change (we are not stable yet), I just need to know it to ensure the appropriate communication and versioning 😊

I can improve coverage issue with write more test case, Do you want?

**Comment by curquiza** [comment]
> I can improve coverage issue with write more test case, Do you want?

Yes you can, thank you 😊 but it was not my question. Sorry I was not clear

Does your PR introduce breaking change regarding the usage for the library users? Something they could do before they have to do differently?

**Comment by Ja7ad** [comment]
> > I can improve coverage issue with write more test case, Do you want?
> 
> Yes you can, thank you 😊 but it was not my question. Sorry I was not clear
> 
> Does your PR introduce breaking change regarding the usage for the library users? Something they could do before they have to do differently?

No

**Comment by curquiza** [comment]
> @curquiza I think task request have similar issue, Do you want fix it in this PR?

Please 🙏  thank you very much for your contributions

**Comment by Ja7ad** [comment]
> > @curquiza I think task request have similar issue, Do you want fix it in this PR?
> 
> Please 🙏 thank you very much for your contributions

We have an issue with `TaskQuery`.

For `UIDs` we used `[]int64` but in API body get `"1,2,3,4...n"`

https://github.com/meilisearch/meilisearch-go/blob/869e74304eae91d70de5a9ac814c55b4683f33c4/client.go#L573-L581

**Comment by curquiza** [comment]
> We can don't change it as default not have issue.

I'm not sure I understand what you mean. Do you mean we cannot fix it?

If it's this, no issue, I merge this PR without it

**Review by curquiza — APPROVED** [review]
bors merge

**Pull request merged**
