### PR TITLE
Fix issue with ticker leaking CPU, optimize

### LINKED ISSUE #522: WaitForTask leaking CPU usage
**Description**
WaitForTask using CPU when Idle (simulation included)

**Expected behavior**
0 % CPU 

**Current behavior**
4000 Calls to WaitForTask causing 10-15% CPU usage

**Screenshots or Logs**
Arch:
image
MacOS:
image

**Environment (please complete the following information):**
- OS: Tested on Arch kernel 6.8.1 and MacOS 14.4(M2)
- Meilisearch version: v.1.7.5
- meilisearch-go version: v0.26.2

Simulation code:

https://gist.github.com/thisisdev-patrick/da24fb4757820c611e2ea696d2e93953

### PR DESCRIPTION
**Pull request by thisisdev-patrick**
https://github.com/meilisearch/meilisearch-go/issues/522

# Pull Request

## Related issue
Fixes #522

## What does this PR do?
- fixes ticker CPU leakage on the WaitForTask method. I also optimized the method to first check and then start a ticker if needed. Also added some missing unit test for the GetTasks method using the the client package, which is totally unrelated but needed to get to the codecov threshold

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by thisisdev-patrick** [comment]
@curquiza can you please rerun the workflow? I've added some ut's for unrelated stuff in this PR, I was a victim of poor previous work :) thanks, it would help us a lot if this fix gets released asap. Thanks in advance!

**Comment by thisisdev-patrick** [comment]
I could add some codecov ignores with your permission? https://community.codecov.com/t/ignore-lines-with-comments-inside-the-files-expected-misses/2661

**Comment by curquiza** [comment]
> I could add some codecov ignores with your permission? https://community.codecov.com/t/ignore-lines-with-comments-inside-the-files-expected-misses/2661

Yes please 🙏

**Comment by thisisdev-patrick** [comment]
Sorry I screwed up; those tags were a suggestion by some user.. I'll remove them and try to find a solution; please do not merge yet

**Comment by curquiza** [comment]
Can I merge @thisisdev-patrick? 😊

**Comment by thisisdev-patrick** [comment]
yes :)

**Review by curquiza — APPROVED** [review]
bors merge

**Comment by curquiza** [comment]
doing a release this afternoon!

**Pull request merged**
