### PR TITLE
Add support for vectorSearch (v1.3)

### LINKED ISSUE #465: [v1.3] [EXPERIMENTAL] Vector Store
⚠️ This issue is generated, it means the examples and the namings do not necessarily correspond to the language of this repository.
Also, if you are a maintainer, feel free to add any clarification and instruction about this issue.

Sorry if this is already partially/completely implemented, feel free to let me know about the state of this issue in the repo.

Related to https://github.com/meilisearch/integration-guides/issues/280

----

### New implementation

:warning: A disclaimer about labeled EXPERIMENTAL features:

> To ensure we still deliver stability to our users and have ways to innovate. Meilisearch has a way to opt-in for experimental features. The user must query a particular route and enable/disable those features.
The SDKs receiving the experimental features will likely change soon (a.k.a: breaking changes), which will not trigger a major version update.
So, before adopting a **experimental feature**, be sure what you're doing.

Related to:
- issue: https://github.com/meilisearch/meilisearch/issues/3798
- spec: https://github.com/meilisearch/specifications/pull/248

It allows the user to store dense vectors to be retrieved later during search time.

What needs to be changed:

- Ensure sending the `vector` key during the search works: `client.index('myindex').search('query', { vector: [0.1, ...] })` 
- Ensure it is possible to send during the data ingestion the `_vectors` special field in the documents: `client.index('myindex').add_documents({ _vectors: [0.1, ...] })`
- The response can contain a `vector` key similar to the `q` key.

:warning: This feature is enabled by querying `PATCH /experimental-features` with `{ "vectorStore": true }`

**Extra:** Add inline documentation for the method, explaining the availability of this feature only for Meilisearch v1.3 and newer. And that is also an experimental feature that needs to be opt-in manually using the `/experimental-features` https://github.com/meilisearch/meilisearch/issues/3857 endpoint.

TODO:
- [ ] Add the ability receive a new param in the search request called `vector`.
- [ ] Add the ability handle a `vector` key in the response.
- [ ] Add integration tests (don't forget to enable the experimental feature)

### PR DESCRIPTION
**Pull request by luigibarbato**
# Pull Request

## Related issue
Fixes #465 
## What does this PR do?
- [x] Add the ability receive a new param in the search request called vector.
- [x] Add the ability handle a vector key in the response.
- [x] Add integration tests
## PR checklist
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

### CODE REVIEW

**Review by alallema — COMMENTED** [review]
Thanks, @luigibarbato, for this PR!
The tests are failing because `vectorSerach` is an experimental feature that needs to be enabled.
I don't recommend that you create the method to activate the experimental functionality but rather make a call to the route with `net/http` or another package like resty as you wish.
You can see [here](https://github.com/meilisearch/meilisearch-python/pull/805/files) how the feature and tests have been implemented in python in case it's help

**Comment by luigibarbato** [comment]
@alallema there is a problem between `easyjson` and `codecov` 😄

**Comment by alallema** [comment]
> @alallema there is a problem between easyjson and codecov 😄

I won't be able to help you with that, @brunoocasali could check that?

**Comment by brunoocasali** [comment]
Hi @luigibarbato can you add this file:

```yml
# codecov.yml
ignore:
  - "easyjson_types*.go" 
```

**Comment by luigibarbato** [comment]
@alallema @brunoocasali Here we go! 🪂 🥳

**Review by alallema — APPROVED** [review]
Thanks @luigibarbato for this PR ❤️ 
LGTM! 🎉

**Comment by alallema** [comment]
bors merge

**Pull request merged**
