### PR TITLE
Moving to fasthttp client

### PR DESCRIPTION
**Pull request by senyast4745**
# Summary
In this pull request, we switched to `fasthttp.Client` and `easyjson` to increase performance and so for more flexibility in use.

# Changes

1. Changed standard `http.Client` to `fasthttp.Client`

2. `easyjson` was used to accelerate the serialization / deserialization of standard objects

3. Added several custom types for faster and more convenient processing, such as `RawType`

4. Fixed tests

# Closes

issue #86

### CODE REVIEW

**Review by eskombro — CHANGES_REQUESTED** [review]
Thanks, this is an amazing job @senyast4745 and it seems to be working quite well!

A few comments/questions:

1. I don't think we need to rename everything with the prefix `fast`, not only this isn't necessary but introduces a lot of codebase change for any earlier project with no benefits. And if any other Http client is implemented, it needs to be changed everywhere again. So could you please not add the names modifications that involve just adding `fast` to the namings? (or do you think this actually adds some value / it is important?)

2. Same with creating an Str alias for string, I don't understand what purpose it serves, but I think it introduces unnecessary complexity.

Otherwise, this seems to be a great addition! 🎉

**Comment by senyast4745** [comment]
@eskombro I have corrected your remarks

**Comment by eskombro** [comment]
Thanks @senyast4745 ! 🎉 

Just FYI we encourage everyone to create a PR from a branch created in their Fork instead of doing it from their own Master, it is a good practice! For example, if your PR was not merged etc, you would have had a broken `master` branch compared to ours. I'm saying this for the next time, let's keep it like this for this PR. 😉 

Also, we had a little issue and had to push force some commits and rewrite the history of the repo, so it is possible that you have a conflict after we merge this, please try to update your repo. You can for example (after we merge) checkout on your own master, and do `git reset --hard <the-name-of-our-origin-in-your-machine>/master` and push force it to your own repo. I am really sorry about this.

**Review by eskombro — APPROVED** [review]

**Comment by senyast4745** [comment]
> Thanks @senyast4745 ! 🎉
> 
> Just FYI we encourage everyone to create a PR from a branch created in their Fork instead of doing it from their own Master, it is a good practice! For example, if your PR was not merged etc, you would have had a broken `master` branch compared to ours. I'm saying this for the next time, let's keep it like this for this PR. 😉
> 
> Also, we had a little issue and had to push force some commits and rewrite the history of the repo, so it is possible that you have a conflict after we merge this, please try to update your repo. You can for example (after we merge) checkout to your own master, and do `git reset --hard <the-name-of-our-origin-in-your-machine>/master` and push force it to your own repo. I am really sorry about this.

Thank you, I will take into account your comments in the next PR

**Pull request merged**
