### PR TITLE
Update version for the next release (v0.20.0)

### PR DESCRIPTION
**Pull request by alallema**
This version makes this package compatible with Meilisearch v0.28.0 :tada:
Check out the changelog of [Meilisearch v0.28.0](https://github.com/meilisearch/meilisearch/releases/tag/v0.28.0) for more information on the changes.

## 💥 Breaking changes

- `Index.Search` changes in the response fields: #306
    - `nbHits` replaced with `estimatedTotalHits`
    - `exhaustiveNbHits` is deleted
    - `exhaustiveFacetsCount` is deleted
  - `facetsDistribution` response parameter is renamed `facetDistribution`.
- `Index.Search` changes in the request parameters:  #306
  - `matches` renamed `showMatchesPosition`
  - `facetsDistribution` request parameter is renamed `facets`.
- `Index.GetDocuments()` and `Index.GetDocument()` request parameters: #314
  - `attributesToRetrieve` replaced with `fields`.
- `Index.GetTasks()` has additional parameters for filtering: `type`, `status` and `indexUid`. #310
- All asynchronous methods now return a struct`TaskInfo` instead of 'Task' like `AddDocuments` or `CreateIndex`. #310
- `Index.GetTasks` and `Client.GetTasks` accept pagination metadata, added `limit` (default: 20), `from`. #310
- `Client.GetAllIndexes` and `Client.GetAllRawIndexes` now returns an `IndexesResults` struct containing the following fields: `Results`, `Limit`, `Offset`, `Total`. #312 
- `Client.GetAllIndexes` accept pagination metadata, added `limit` (default: 20) and `offset` (default: 0). #312
- The `IndexUid` field in both `TaskInfo` and `Task` can be nil Update tasks routes #313
- `Index.GetDocuments` and `Client.GetDocuments` now returns an `DocumentsResults` struct containing the following fields: `Results`, `Limit`, `Offset`, `Total`. #314
- `Client.GetDumpStatus` has been removed #311
- `Client.CreateDump()` now returns an `TaskInfo` #321 
- `Client.GenerateTenantToken(APIKeyUID string, SearchRules map[string]interface{}, Options *TenantTokenOptions)` has now a mandatory `APIKeyUID` parameter which should contain the uid of a specific API key. #315
- `Index.GetDocuments` now accepts pagination parameters: `limit` (default: 20) and `offset` (default: 0). #314
- `Client.GetKeys` accept pagination metadata, added `limit` (default: 20) and `offset` (default: 0). #313
- `Client.UpdateKey` now can just update the `Description` and/or the `Name`. #313
- `Key` now has an additional `Name` field. #313

## 🚀 Enhancements

- `Client.GetKeys(param *KeysQuery)` can now also find keys based on their key uid. #313
- `Client.CreateKey(request *Key)` lets you specify a custom uid (optionally) to create a new Key. #313

Thanks again to @alallema  ! 🎉

### CODE REVIEW

**Comment by bidoubiwa** [comment]
> Add TaskInfo now return but all asynchronous method like AddDocuments or CreateIndex

Not very clear :/ Missing PR link as well

**Comment by bidoubiwa** [comment]
Missing breaking (pasted from JS so needs to be updated): 

- client.updateKey(key: string, options: KeyPayload): Promise<Key> now can just update the description and/or the name.
- Key now has an additional `name` field
- The indexUid field in both EnqueuedTask and Task can be null Update tasks routes  #1259

**Comment by bidoubiwa** [comment]
Oh and at the end: 

```
Thanks again to @alallema  ! 🎉
```

<3

**Review by bidoubiwa — APPROVED** [review]
LGTM 🔥🔥🔥🔥🔥🔥🔥🔥🔥

**Comment by alallema** [comment]
bors merge

**Pull request merged**
